all:
	$(MAKE) -C simple_process
	$(MAKE) -C ltp-pan
	$(MAKE) -C page-types

install:
	$(MAKE) -C simple_process install
	$(MAKE) -C ltp-pan install
	$(MAKE) -C page-types install

clean:
	$(MAKE) -C simple_process clean
	$(MAKE) -C ltp-pan clean
	$(MAKE) -C page-types clean
