all:
	$(MAKE) -C ltp-pan
	$(MAKE) -C page-types
	$(MAKE) -C victim

install:
	$(MAKE) -C ltp-pan install
	$(MAKE) -C page-types install
	$(MAKE) -C victim install

clean:
	$(MAKE) -C ltp-pan clean
	$(MAKE) -C page-types clean
	$(MAKE) -C victim clean
